# Generated by Django 5.2.7 on 2025-10-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True, default=None, max_length=150, null=True, unique=True
            ),
        ),
    ]
