# Generated by Django 5.2.7 on 2025-10-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_lesson_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(default="", verbose_name="Ссылка на видео"),
            preserve_default=False,
        ),
    ]
