# Generated by Django 5.2.7 on 2025-10-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=10000, verbose_name="Цена курса"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(default=1000, verbose_name="Цена урока"),
        ),
    ]
