events {
    worker_connections 1024; # Размер события при соединении с сервером
}

http {
    include /etc/nginx/mime.types; # Разрешаем отдавать и принимать строковые и медиа файлы при http подключении
    default_type application/octet-stream; # Размер процесса (8 бит)

    upstream django {
        server web:8000; # Слушаем джанго приложение веб (из композа), которое работает на порту 8000
    }

    server {
        listen 80; # Слушаем все входящие запросы, которые приходят на порт 80 (будет направлять на 8000)
        server_name _; # как заглушка _

        location /static/ {
            alias /app/staticfiles/; # когда запрашивается статика, брать из app/staticfiles
        }

        location / {
            proxy_pass http://django; # все входяще запросы на 8000 проксируются на http://django
        }
    }
}